// Run: npm install --prefix /tmp/lilo-tests jsdom
// JSDOM_PATH=/tmp/lilo-tests/node_modules/jsdom node tests/regression.cjs
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function app(seed={},blocked=false){const errors=[];const dom=new JSDOM(html,{url:'https://example.test/',runScripts:'dangerously',beforeParse(w){w.addEventListener('error',e=>errors.push(e.message));for(const [key,value] of Object.entries(seed))w.localStorage.setItem(key,value);if(blocked)w.Storage.prototype.setItem=()=>{throw Error('blocked')}}});return {w:dom.window,d:dom.window.document,errors}}
const {w,d,errors}=app();const $=s=>d.querySelector(s),click=s=>$(s).click(),fill=(s,value)=>{$(s).value=value;$(s).dispatchEvent(new w.Event('input',{bubbles:true}))};
const ids=[...d.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length);assert.equal(d.querySelectorAll('.card').length,5);
fill('[data-kg="0"]','12,5');fill('[data-r="0"]','10');click('[data-d^="Martes"]');click('[data-d^="Lunes"]');assert.equal($('[data-kg="0"]').value,'12,5');click('.done');assert.match($('#status').textContent,/repeticiones/);
for(let i=0;i<3;i++){fill(`[data-kg="${i}"]`,'12,5');fill(`[data-r="${i}"]`,'10')}click('.done');assert.deepEqual([...d.querySelectorAll('[data-summary]')].map(x=>x.textContent),['1 de 5 ejercicios completados','1 de 5 ejercicios completados']);assert([...d.querySelectorAll('[data-bar]')].every(x=>x.style.width==='20%'));
const seed=Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]));const reload=app(seed);assert.equal(reload.d.querySelector('.done').textContent,'✓ Completado');reload.w.close();
for(const name of ['progress','nutrition','records','train']){click(`[data-v="${name}"]`);assert.equal($('.view.active').id,name)}click('[data-v="records"]');assert.match($('#recordList').textContent,/12.5 kg × 10/);click('[data-v="progress"]');click('#saveP');assert.match($('#status').textContent,/medición válida/);fill('#pw','62,5');click('#saveP');assert.match($('#pRows').textContent,/62.5/);assert.equal(JSON.parse(w.localStorage.v5progress)[0].w,'62.5');
click('[data-v="train"]');fill('#q','prensa');assert.equal([...d.querySelectorAll('.card')].filter(x=>x.style.display!=='none').length,1);fill('#q','');
click('#tb');w.eval('deadline=Date.now()-1;tick()');assert.equal($('#tm').textContent,'00:00');d.querySelectorAll('button').forEach(b=>{if(b.textContent==='Reiniciar descanso')b.click()});assert.equal($('#tm').textContent,'02:00');click('#tb');click('#tb');assert.equal(w.eval('deadline'),null);
for(const day of ['Lunes','Martes','Miércoles','Jueves','Viernes']){click(`[data-d^="${day}"]`);for(const a of d.querySelectorAll('.videoBtn')){assert.equal(new URL(a.href).hostname,'www.youtube.com');assert.equal(a.target,'_blank');assert(a.rel.includes('noopener'))}}
w.eval("sessionDate='2000-01-01';ensureDate()");assert.equal($('[data-summary]').textContent,'0 de 6 ejercicios completados');assert.deepEqual(errors,[]);w.close();
for(const seed of [{v5logs:'{broken',v5progress:'invalid',v5day:'missing'},{v5logs:JSON.stringify({'x':[null,{}, {sets:[null]}]}),v5progress:'{}'}]){const a=app(seed);assert.equal(a.d.querySelectorAll('.card').length,5);assert.deepEqual(a.errors,[]);a.w.close()}
const blocked=app({},true);blocked.d.querySelector('[data-v="progress"]').click();blocked.d.querySelector('#pw').value='60';blocked.d.querySelector('#saveP').click();assert.equal(blocked.d.querySelector('#pw').value,'60');assert.match(blocked.d.querySelector('#status').textContent,/No se pudo guardar/);blocked.w.close();
// Exercise real service-worker handlers using controlled network and cache adapters.
const handlers={},cache=new Map(),deleted=[];let offline=false,claimed=false,skipped=false;
const context={URL,Response,Promise,self:{location:{origin:'https://example.test'},registration:{scope:'https://example.test/'},addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting:async()=>{skipped=true},clients:{claim:async()=>{claimed=true}}},caches:{open:async()=>({addAll:async assets=>assets.forEach(a=>cache.set(a,new Response(a))),put:async(req,res)=>cache.set(req.url,res),match:async req=>cache.get(typeof req==='string'?req:req.url)}),keys:async()=>['mi-entrenamiento-v5-1','unrelated-cache'],delete:async key=>deleted.push(key)},fetch:async()=>{if(offline)throw Error('offline');return new Response('network')}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),context);
(async()=>{await new Promise((resolve,reject)=>handlers.install({waitUntil:p=>p.then(resolve,reject)}));assert(skipped);await new Promise((resolve,reject)=>handlers.activate({waitUntil:p=>p.then(resolve,reject)}));assert(claimed);assert.deepEqual(deleted,['mi-entrenamiento-v5-1']);
async function request(url,mode='navigate'){let response;handlers.fetch({request:{url,method:'GET',mode},respondWith:p=>response=p});return response}
assert.equal(await request('https://youtube.com/watch?v=x'),undefined);assert.equal(await request('https://example.test/missing.png','no-cors'),undefined);offline=true;assert.equal(await (await request('https://example.test/')).text(),'./index.html');offline=false;assert.equal(await (await request('https://example.test/')).text(),'network');console.log('PASS: IDs, scoped progress, navigation, drafts, reload, validation, records, filtering, timer, video links, date rollover, storage failures and PWA cache handlers.');})().catch(e=>{console.error(e);process.exitCode=1});
